qtbase: Add libxi to depends.
Not having so gives errors like this when configuring qtbase

XInput2 auto-detection... ()
compiling /home/teamcitybuildagent/work/33644ecacd0fdba5/build/tmp/work/i586-poky-linux/qtbase/5.1.1-r0/qtbase-opensource-src-5.1.1/config.tests/x11/xinput2/xinput2.cpp
/home/teamcitybuildagent/work/33644ecacd0fdba5/build/tmp/work/i586-poky-linux/qtbase/5.1.1-r0/qtbase-opensource-src-5.1.1/config.tests/x11/xinput2/xinput2.cpp:43:36: fatal error: X11/extensions/XInput2.h: No such file or directory
                                   ^
compilation terminated.
make: *** [xinput2.o] Error 1
XInput2 disabled.
XInput2 support cannot be enabled due to functionality tests!
Turn on verbose messaging (-v) to /home/teamcitybuildagent/work/33644ecacd0fdba5/build/tmp/work/i586-poky-linux/qtbase/5.1.1-r0/qtbase-opensource-src-5.1.1/configure to see the final report.
If you believe this message is in error you may use the continue
switch (-continue) to /home/teamcitybuildagent/work/33644ecacd0fdba5/build/tmp/work/i586-poky-linux/qtbase/5.1.1-r0/qtbase-opensource-src-5.1.1/configure to continue.